name: Release Test
description: Issue template for release test
title: "v リリーステスト"
body:
  - type: textarea
    id: template
    attributes:
      description: 案件の一覧等を入力して送信してください（送信後でも編集できます）
      value: "
## 各案件状況

Merged for master: 🟣

Test pass: 🟢

Test fail or require update or require review: 🔴

Conflict: 🟤


### AIRCLOSET-XXXXX 案件名


## リリテス用ブランチ

CI pass: 🟢

CI fail: 🔴


🟢 https://github.com/air-closet/air-closet/pull/


マージコミットを確認したいときは `git log --oneline --first-parent master` が便利。


## テスト進捗


開始：

終了予定：


## TODO

1. テスト作成（テスト開始の2W前までに提出）

  - [ ] AIRCLOSET-47727 サービス側からみんなのコーデ画像を投稿する機能

  - [ ] AIRCLOSET-53463 チャネルトーク再開

2. アプリ以外のProdリリース

  - [ ] AIRCLOSET-47727 サービス側からみんなのコーデ画像を投稿する機能

  - [ ] AIRCLOSET-53463 チャネルトーク再開

3. 回帰テスト準備

  - [ ] アプリ配布リンクを作成する（AppVersion毎にリンク作成）

  - [ ] ハイテク側にDeployGateリンクを渡す

    - [ ] iOS

    - [ ] Android

  - [ ] STGリリース

    - [ ] API

    - [ ] Migration

  - [ ] [本番環境の画像をStg環境にコピー](https://air-closet.esa.io/posts/182)

4. 審査出し

  - [ ] Store画像を全端末分確認

  - [ ] AppVersionUp

  - [ ] CodePush用VersionUp

  - [ ] タグを切る

  - [ ] リリース審査出す時に、前回のアプリ担当者と一緒にやりますか？

  - [ ] 審査に出す

    - [ ] ios

    - [ ] android

6. 社内検証・QA対応

  - [ ] 社内検証実施

    - [ ] [TestRail](https://aircloset.testrail.io/index.php?/runs/view/1185&group_by=cases:section_id&group_order=asc)

  - [ ] 日次QA対応

  - [ ] 不具合対応

  - [ ] 回帰テストの誤りを修正する

7. アプリリリース

  - [ ] CTO確認

  - [ ] 最終確認

  - [ ] リリース
"
    validations:
      required: true
